import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import SVGtoPDF from "svg-to-pdfkit";

const formatINR = (n) => `₹${Number(n || 0).toLocaleString("en-IN")}`;

const formatShortId = (id, len = 8) => {
  if (!id) return "—";
  return String(id).slice(-len).toUpperCase();
};

const safeText = (v, fallback = "—") => {
  if (v === null || v === undefined) return fallback;
  const s = String(v).trim();
  return s.length ? s : fallback;
};

const getLogoSvgContent = () => {
  try {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = path.dirname(__filename);
    const logoPath = path.resolve(__dirname, "../../../frontend/src/assets/images/logo.svg");
    return fs.readFileSync(logoPath, "utf8");
  } catch {
    return null;
  }
};

const COLORS = {
  primary: "#2563EB",
  secondary: "#1E40AF",
  text: "#1F2937",
  muted: "#6B7280",
  light: "#9CA3AF",
  line: "#E5E7EB",
  headerFill: "#F8FAFC",
  tableHeaderFill: "#F1F5F9",
  zebra: "#F8FAFC",
  white: "#FFFFFF",
};

const LAYOUT = {
  marginLeft: 50,
  marginRight: 50,
  marginTop: 130, // reserved for top header
  marginBottom: 70, // reserved for footer
};

const drawHeader = (doc, { title, subtitle, logoSvg }) => {
  const left = 50;
  const right = doc.page.width - 50;
  const width = right - left;
  const top = 30;
  const headerHeight = 70;

  // Background rect for header area optionally
  doc.save();
  doc.roundedRect(left, top, width, headerHeight, 6).fill(COLORS.headerFill);
  doc.restore();

  const logoX = left + 20;
  const logoY = top + 15;
  const logoW = 50;
  const logoH = 40;

  let logoRendered = false;
  if (logoSvg) {
    try {
      SVGtoPDF(doc, logoSvg, logoX, logoY, {
        width: logoW,
        height: logoH,
        preserveAspectRatio: "xMidYMid meet",
      });
      logoRendered = true;
    } catch {
      logoRendered = false;
    }
  }

  if (!logoRendered) {
    doc
      .font("Helvetica-Bold")
      .fillColor(COLORS.primary)
      .fontSize(18)
      .text("CargoLink", logoX, logoY + 12);
  }

  // Title and subtitle on the right
  const textLeft = logoX + 80;
  doc
    .font("Helvetica-Bold")
    .fillColor(COLORS.text)
    .fontSize(16)
    .text(title, textLeft, top + 18, { align: "right", width: right - textLeft - 20 });
  
  doc
    .font("Helvetica")
    .fillColor(COLORS.muted)
    .fontSize(10)
    .text(subtitle, textLeft, top + 40, { align: "right", width: right - textLeft - 20 });
};

const drawFooter = (doc, { pageNumber, totalPages }) => {
  const left = 50;
  const right = doc.page.width - 50;
  const y = doc.page.height - 50;

  doc.moveTo(left, y - 10).lineTo(right, y - 10).lineWidth(1).strokeColor(COLORS.line).stroke();

  doc.fillColor(COLORS.light).font("Helvetica").fontSize(9);
  doc.text("Generated by CargoLink Logistics Platform", left, y, { align: "left" });
  doc.text("contact@cargolink.com | www.cargolink.com", left, y, { align: "center", width: right - left });
  doc.text(`Page ${pageNumber} of ${totalPages}`, left, y, { align: "right", width: right - left });
};

const drawSectionTitle = (doc, title) => {
  doc.moveDown(1.5);
  doc.font("Helvetica-Bold").fillColor(COLORS.secondary).fontSize(14).text(title);
  doc.moveDown(0.5);
  
  const startX = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  doc.moveTo(startX, doc.y - 5).lineTo(startX + width, doc.y - 5).lineWidth(1).strokeColor(COLORS.primary).stroke();
  doc.moveDown(0.5);
};

const drawDetailsGrid = (doc, title1, details1, title2, details2) => {
  doc.moveDown(1);
  
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const mid = left + (right - left) / 2 + 10;
  const boxWidth = (right - left) / 2 - 10;
  
  // Section layout
  const startY = doc.y;
  
  const checkSpace = (needed) => {
    if (doc.y + needed > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      return true;
    }
    return false;
  };

  checkSpace(130);
  
  const currentStartY = doc.y;

  // Box 1
  doc.roundedRect(left, currentStartY, boxWidth, 110, 4).lineWidth(1).strokeColor(COLORS.line).stroke();
  doc.roundedRect(left, currentStartY, boxWidth, 25, 4).fill(COLORS.tableHeaderFill);
  doc.font("Helvetica-Bold").fillColor(COLORS.text).fontSize(11).text(title1, left + 10, currentStartY + 8);
  
  let currentY1 = currentStartY + 35;
  details1.forEach(d => {
    doc.font("Helvetica-Bold").fillColor(COLORS.muted).fontSize(9).text(d.label + ":", left + 10, currentY1);
    doc.font("Helvetica").fillColor(COLORS.text).fontSize(9).text(d.value, left + 80, currentY1, { width: boxWidth - 90 });
    currentY1 += 16;
  });

  // Box 2
  doc.roundedRect(mid, currentStartY, boxWidth, 110, 4).lineWidth(1).strokeColor(COLORS.line).stroke();
  doc.roundedRect(mid, currentStartY, boxWidth, 25, 4).fill(COLORS.tableHeaderFill);
  doc.font("Helvetica-Bold").fillColor(COLORS.text).fontSize(11).text(title2, mid + 10, currentStartY + 8);
  
  let currentY2 = currentStartY + 35;
  details2.forEach(d => {
    doc.font("Helvetica-Bold").fillColor(COLORS.muted).fontSize(9).text(d.label + ":", mid + 10, currentY2);
    doc.font("Helvetica").fillColor(COLORS.text).fontSize(9).text(d.value, mid + 80, currentY2, { width: boxWidth - 90 });
    currentY2 += 16;
  });

  doc.y = Math.max(currentY1, currentY2) + 15;
};

const drawLineItemsTable = (doc, items) => {
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const tableWidth = right - left;
  const col1Width = tableWidth - 120;
  const col2Width = 120;
  
  const checkSpace = (needed) => {
    if (doc.y + needed > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      return true;
    }
    return false;
  };

  const drawHeaderRow = () => {
    const y = doc.y;
    doc.roundedRect(left, y, tableWidth, 25, 4).fillAndStroke(COLORS.tableHeaderFill, COLORS.line);
    doc.font("Helvetica-Bold").fillColor(COLORS.text).fontSize(10);
    doc.text("Description", left + 10, y + 8, { width: col1Width - 20, lineBreak: false });
    doc.text("Amount", left + col1Width + 10, y + 8, { width: col2Width - 20, align: "right", lineBreak: false });
    doc.y = y + 25;
  };

  drawHeaderRow();

  doc.font("Helvetica").fontSize(10);
  items.forEach((it, i) => {
    if (checkSpace(25)) {
      drawHeaderRow();
      doc.font("Helvetica").fontSize(10);
    }
    
    const y = doc.y;
    if (i % 2 !== 0) {
      doc.rect(left, y, tableWidth, 24).fill(COLORS.zebra);
      doc.fillColor(COLORS.text);
    } else {
      doc.fillColor(COLORS.text);
    }
    
    doc.text(safeText(it.label), left + 10, y + 8, { width: col1Width - 20, lineBreak: false });
    doc.text(safeText(it.value), left + col1Width + 10, y + 8, { width: col2Width - 20, align: "right", lineBreak: false });
    doc.y = y + 24;
  });

  doc.moveTo(left, doc.y).lineTo(right, doc.y).lineWidth(1).strokeColor(COLORS.line).stroke();
  doc.moveDown(1);
};

const buildBreakdownItems = (bid) => {
  const breakdown = bid?.quote_breakdown;
  if (!breakdown) return [];

  const items = [];
  items.push({ label: "Transportation Charges", value: formatINR(breakdown.transportation_charges) });

  if (breakdown.packing_included) items.push({ label: "Packing Cost", value: "Included" });
  else if ((breakdown.packing_cost ?? 0) > 0) items.push({ label: "Packing Cost", value: formatINR(breakdown.packing_cost) });

  if (breakdown.loading_included) items.push({ label: "Loading Charges", value: "Included" });
  else if ((breakdown.loading_charges ?? 0) > 0) items.push({ label: "Loading Charges", value: formatINR(breakdown.loading_charges) });

  if ((breakdown.toll_cost ?? 0) > 0) items.push({ label: "Toll Cost", value: formatINR(breakdown.toll_cost) });
  if ((breakdown.octroi_entry_tax ?? 0) > 0)
    items.push({ label: "Octroi / Entry Tax", value: formatINR(breakdown.octroi_entry_tax) });
  if ((breakdown.storage_charges ?? 0) > 0) items.push({ label: "Storage Charges", value: formatINR(breakdown.storage_charges) });

  if (Array.isArray(breakdown.custom_items)) {
    breakdown.custom_items.forEach((ci) =>
      items.push({
        label: safeText(ci?.label, "Custom"),
        value: formatINR(ci?.amount),
      })
    );
  }

  if ((breakdown.gst?.amount ?? 0) > 0)
    items.push({
      label: `GST (${safeText(breakdown.gst?.rate_percent, "—")}%)`,
      value: formatINR(breakdown.gst.amount),
    });

  return items;
};

const generateQuotePdf = (stream, order, bid) => {
  const transporter = bid?.transporter_id;

  const doc = new PDFDocument({ 
    size: "A4", 
    margins: { left: LAYOUT.marginLeft, right: LAYOUT.marginRight, top: LAYOUT.marginTop, bottom: LAYOUT.marginBottom },
    bufferPages: true 
  });
  
  doc.pipe(stream);

  const logoSvg = getLogoSvgContent();

  const title = "Transportation Quotation";
  const subtitle = `Generated: ${new Date().toLocaleString("en-IN")}`;

  // Start Content
  
  // Summaries
  drawSectionTitle(doc, "Quotation Details");
  
  drawDetailsGrid(doc, 
    "Order Information", [
      { label: "Order ID", value: `#${formatShortId(order?._id)}` },
      { label: "Bid ID", value: `#${formatShortId(bid?._id)}` },
      { label: "Date", value: new Date().toLocaleDateString("en-IN") },
      { label: "Status", value: safeText(bid?.status, "Pending").toUpperCase() },
    ],
    "Transporter Details", [
      { label: "Company", value: safeText(transporter?.company_name || transporter?.name, "N/A") },
      { label: "Contact", value: safeText(transporter?.primary_contact, "N/A") },
      { label: "Email", value: safeText(transporter?.email, "N/A") },
      { label: "Phone", value: safeText(transporter?.phone_number, "N/A") },
    ]
  );
  
  drawSectionTitle(doc, "Shipment Details");
  drawDetailsGrid(doc,
    "Pickup & Delivery", [
      { label: "Pickup City", value: `${safeText(order?.pickup?.city, "N/A")}${order?.pickup?.state ? ", " + order.pickup.state : ""}` },
      { label: "Delivery City", value: `${safeText(order?.delivery?.city, "N/A")}${order?.delivery?.state ? ", " + order.delivery.state : ""}` },
      { label: "Distance", value: `${safeText(order?.distance, "—")} km` },
    ],
    "Cargo Information", [
      { label: "Truck Type", value: safeText(order?.truck_type, "—") },
      { label: "Goods Type", value: safeText(order?.goods_type, "—") },
      { label: "Weight", value: `${safeText(order?.weight, "—")} kg` },
    ]
  );

  drawSectionTitle(doc, "Financial Breakdown");

  const breakdownItems = buildBreakdownItems(bid);
  if (!breakdownItems.length) {
    doc.font("Helvetica").fillColor(COLORS.muted).fontSize(10).text("No detailed breakdown available.", { align: "center" });
    doc.moveDown(1);
  } else {
    drawLineItemsTable(doc, breakdownItems);
  }

  // Total
  const left = LAYOUT.marginLeft;
  const right = doc.page.width - LAYOUT.marginRight;
  
  if (doc.y + 100 > doc.page.height - doc.page.margins.bottom) {
    doc.addPage();
  }

  doc.moveDown(0.5);
  
  const totalBoxWidth = 250;
  const totalBoxX = right - totalBoxWidth;
  doc.roundedRect(totalBoxX, doc.y, totalBoxWidth, 40, 6).fillAndStroke(COLORS.primary, COLORS.primary);
  
  doc.font("Helvetica").fillColor(COLORS.white).fontSize(12).text("Total Amount", totalBoxX + 15, doc.y + 13, { lineBreak: false });
  doc.font("Helvetica-Bold").fillColor(COLORS.white).fontSize(16).text(formatINR(bid?.bid_amount), totalBoxX, doc.y + 11, { width: totalBoxWidth - 15, align: "right", lineBreak: false });
  
  // Note section
  doc.y += 60;
  doc.rect(left, doc.y, right - left, 40).fill(COLORS.zebra);
  doc.font("Helvetica-Bold").fillColor(COLORS.muted).fontSize(10).text("Note:", left + 10, doc.y + 10);
  doc.font("Helvetica").fillColor(COLORS.muted).fontSize(9).text("This quotation is subject to terms and conditions. Prices may vary based on exact load and route conditions at the time of transport.", left + 45, doc.y + 10, { width: right - left - 55 });

  // Add Headers and Footers to all pages
  const range = doc.bufferedPageRange();
  
  for (let i = range.start, end = range.start + range.count, pageIndex = 1; i < end; i++, pageIndex++) {
    doc.switchToPage(i);
    
    // Disable margins to prevent triggering new pages
    const oldMargins = doc.page.margins;
    doc.page.margins = { top: 0, bottom: 0, left: 0, right: 0 };
    
    drawHeader(doc, { title, subtitle, logoSvg });
    drawFooter(doc, { pageNumber: pageIndex, totalPages: range.count });
    
    // Restore margins
    doc.page.margins = oldMargins;
  }

  doc.end();
};

export default generateQuotePdf;